"use client";
import { useState } from "react";
import type { PriceEntry } from "@/lib/catalog/pricing-types";
type Product = { id: string; name: string; slug: string; category: string; entry?: PriceEntry };
const money = (paise?: number | null) => paise == null ? "" : String(Math.round(paise / 100));

export function ProductPricingManager({ products }: { products: Product[] }) {
  const [items, setItems] = useState(products); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState<string | null>(null);
  const update = (id: string, patch: Partial<PriceEntry>) => setItems((current) => current.map((item) => item.id === id ? { ...item, entry: { kind: "indicative_fixed", source: "admin", approved: false, unit: "per model", ...(item.entry ?? {}), ...patch } as PriceEntry } : item));
  async function save(product: Product) { if (!product.entry) return; setSaving(product.id); setNotice(""); const response = await fetch(`/api/admin/products/${product.id}/pricing`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(product.entry) }); setSaving(null); setNotice(response.ok ? `${product.name} pricing saved.` : "Could not save the price. Check the amount and range."); }
  return <><p aria-live="polite" className="mb-4 text-sm text-neutral-600">{notice}</p><div className="overflow-x-auto rounded-2xl border border-[#d6c8b5] bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#eee4d5] text-xs uppercase tracking-wider"><tr><th className="p-4">Product</th><th className="p-4">Pricing mode</th><th className="p-4">Indicative price / range</th><th className="p-4">Unit & status</th><th className="p-4">Save</th></tr></thead><tbody>{items.map((product) => { const entry = product.entry ?? { kind: "indicative_fixed" as const, source: "admin" as const, approved: false, unit: "per model", amount_paise: 0 }; const range = entry.kind === "indicative_range"; return <tr className="border-t border-[#e7dccb] align-top" key={product.id}><td className="p-4"><p className="font-semibold">{product.name}</p><p className="mt-1 text-xs text-neutral-500">{product.category}</p></td><td className="p-4"><select className="rounded border border-[#d6c8b5] bg-white p-2" onChange={(event) => update(product.id, { kind: event.target.value as PriceEntry["kind"] })} value={entry.kind}><option value="indicative_fixed">Indicative fixed</option><option value="indicative_range">Indicative range</option></select></td><td className="p-4">{range ? <div className="flex gap-2"><input aria-label={`${product.name} minimum INR`} className="w-24 rounded border border-[#d6c8b5] p-2" min="0" onChange={(event) => update(product.id, { min_paise: Number(event.target.value) * 100 })} type="number" value={money(entry.min_paise)} /><input aria-label={`${product.name} maximum INR`} className="w-24 rounded border border-[#d6c8b5] p-2" min="0" onChange={(event) => update(product.id, { max_paise: event.target.value ? Number(event.target.value) * 100 : null })} placeholder="Max" type="number" value={money(entry.max_paise)} /></div> : <input aria-label={`${product.name} indicative INR`} className="w-32 rounded border border-[#d6c8b5] p-2" min="0" onChange={(event) => update(product.id, { amount_paise: Number(event.target.value) * 100 })} type="number" value={money(entry.amount_paise)} />}</td><td className="p-4"><input className="w-28 rounded border border-[#d6c8b5] p-2" onChange={(event) => update(product.id, { unit: event.target.value })} value={entry.unit} /><label className="ml-3 whitespace-nowrap text-xs"><input checked={entry.approved} className="mr-1" onChange={(event) => update(product.id, { approved: event.target.checked })} type="checkbox" />Approved</label></td><td className="p-4"><button className="rounded-full bg-[#181818] px-3 py-2 text-xs font-semibold text-white disabled:opacity-50" disabled={saving === product.id} onClick={() => save(product)} type="button">{saving === product.id ? "Saving…" : "Save"}</button></td></tr>; })}</tbody></table></div></>;
}
