-- Apply the approved professional catalogue copy to cards and product pages.
with catalogue(slug, description) as (
  values
    ('ortho-mattress', 'Engineered for firm and balanced support, the Ortho Mattress helps maintain comfortable spinal alignment throughout the night. Its supportive construction evenly distributes body weight while providing a stable sleeping surface. Ideal for those who prefer dependable firmness, comfort, and durability for everyday sleep.'),
    ('ortho-plus-mattress', 'The Ortho Plus Mattress combines enhanced support with additional comfort layers for a more refined sleeping experience. Its balanced construction provides firmness while offering gentle cushioning and pressure relief. A premium choice for customers seeking both support and everyday comfort.'),
    ('latex-mattress', 'Designed with responsive latex, this mattress delivers breathable comfort, gentle bounce, and balanced body support. Its resilient structure adapts naturally to movement while maintaining consistent comfort throughout the night. An excellent option for those seeking durability, ventilation, and premium sleep quality.'),
    ('latex-pro', 'The Latex Pro Mattress features enhanced density and premium comfort layers for superior support and responsiveness. Its breathable construction promotes airflow while providing a comfortable and well-balanced sleeping surface. Designed for customers seeking an elevated combination of luxury, durability, and comfort.'),
    ('pocketed-spring-mattress', 'Featuring individually wrapped springs, this mattress provides targeted support by responding independently to body movement. The advanced spring system helps minimize motion transfer while maintaining excellent comfort and responsiveness. Ideal for couples and sleepers who prefer balanced support with gentle bounce.'),
    ('bonnell-spring-mattress', 'Built with a reliable interconnected spring system, the Bonnell Spring Mattress offers balanced support and responsive comfort. Its traditional coil construction provides gentle bounce while promoting airflow throughout the mattress. A durable and practical solution for comfortable everyday sleeping.'),
    ('foam-mattress', 'The Foam Mattress provides soft, even cushioning for a simple and comfortable sleeping experience. Its lightweight construction makes it easy to handle while delivering consistent support across the sleeping surface. A practical and affordable choice for bedrooms, guest rooms, and everyday use.'),
    ('memory-foam-mattress', 'The Memory Foam Mattress gently contours to the body, providing personalized cushioning and balanced pressure distribution. Its motion-isolating properties help reduce disturbances caused by movement during sleep. Perfect for customers seeking deep comfort, body-conforming support, and a relaxing sleep experience.'),
    ('feel-good-mattress', 'Designed for a soft and relaxing sleep experience, the Feel Good Mattress features plush cushioning with balanced everyday support. Its comfortable surface creates a cozy and inviting environment for restful sleep. An ideal choice for those who prefer softness, simplicity, and everyday comfort.'),
    ('shim-mattress', 'The Shim Mattress offers a compact and versatile sleeping solution for spaces where flexibility is essential. Its lightweight and slim construction makes it suitable as an additional comfort layer or temporary sleeping surface. Perfect for guest rooms, compact spaces, and flexible bedding requirements.'),
    ('l-shape-sofa', 'The L-Shape Sofa combines spacious seating with intelligent corner utilization, making it ideal for modern living rooms. Its extended layout provides generous space for family gatherings, entertainment, and everyday relaxation. A stylish and practical centerpiece for contemporary homes.'),
    ('european-sofa', 'Inspired by contemporary European interiors, this sofa features clean lines, refined proportions, and minimalist elegance. Comfortable cushioning complements its sophisticated design, creating the perfect balance between style and functionality. Ideal for modern and premium living spaces.'),
    ('indian-traditional-sofa', 'The Indian Traditional Sofa combines classic craftsmanship with rich detailing and timeless design. Decorative wooden elements and comfortable upholstery create a warm and elegant living-room atmosphere. Perfect for traditional homes and interiors that celebrate Indian design heritage.'),
    ('head-rest-model-sofa', 'Designed with supportive headrests, this sofa provides enhanced comfort for the head, neck, and upper body. Generous cushioning makes it ideal for extended relaxation, entertainment, and everyday lounging. A perfect combination of ergonomic comfort and contemporary styling.'),
    ('chester-model-sofa', 'Inspired by the timeless Chesterfield design, this sofa features elegant button tufting, structured proportions, and classic detailing. Its luxurious appearance is complemented by comfortable and supportive seating. An excellent statement piece for premium homes, lounges, and office interiors.'),
    ('fiber-back-sofa', 'The Fiber Back Sofa features soft, generously filled back cushions designed to provide exceptional everyday comfort. Its plush cushioning creates a relaxed and inviting seating experience while maintaining adequate support. Ideal for cozy family living rooms and entertainment spaces.'),
    ('prussian-style-sofa', 'The Prussian Style Sofa combines structured lines with refined European-inspired detailing for an elegant appearance. Its sophisticated proportions create a distinctive presence while offering comfortable everyday seating. Perfect for premium residences, formal living rooms, and reception areas.'),
    ('camel-back-sofa', 'Defined by its signature curved backrest, the Camel Back Sofa brings classic elegance and distinctive character to any interior. Comfortable seating complements its graceful silhouette and traditional styling. An excellent choice for sophisticated, vintage-inspired, and traditional living spaces.'),
    ('classic-style-sofa', 'The Classic Style Sofa combines timeless design with comfortable cushioning and balanced proportions. Its versatile appearance allows it to complement both traditional and contemporary interiors effortlessly. A dependable choice for customers seeking long-lasting style and everyday comfort.'),
    ('sofa-with-recliner', 'Combining spacious seating with reclining functionality, this sofa is designed for superior relaxation and personalized comfort. Adjustable seating positions provide enhanced support while watching television, reading, or resting. An ideal addition to family living rooms and entertainment spaces.'),
    ('cloud-sofa', 'The Cloud Sofa delivers an exceptionally soft and luxurious lounging experience through deep seating and plush cushioning. Its relaxed contemporary design creates an inviting atmosphere while providing generous space for relaxation. Perfect for modern interiors where comfort is the highest priority.'),
    ('premium-sofa', 'Crafted with superior materials, refined detailing, and premium cushioning, this sofa delivers an elevated seating experience. Its sophisticated design creates an impressive centerpiece while maintaining exceptional everyday comfort. Ideal for luxurious living rooms and premium interior spaces.'),
    ('cabin-style-sofa', 'The Cabin Style Sofa combines rustic character with soft cushioning to create a warm and inviting seating experience. Its relaxed styling pairs beautifully with wooden finishes and nature-inspired interiors. Perfect for customers seeking comfort, character, and a cozy living-room atmosphere.'),
    ('sectional-sofa', 'The Sectional Sofa features a flexible multi-piece design that can be configured according to different room layouts. Its spacious seating capacity makes it ideal for larger families, gatherings, and entertainment areas. A versatile solution combining functionality, comfort, and modern design.'),
    ('u-shape-sofa', 'Designed with generous seating across three connected sides, the U-Shape Sofa creates the perfect environment for conversations and gatherings. Its spacious configuration offers excellent comfort while becoming a striking living-room centerpiece. Ideal for large families and spacious interiors.'),
    ('corner-sofa', 'The Corner Sofa provides comfortable seating while efficiently utilizing unused corner space. Its compact yet functional design makes it particularly suitable for apartments and smaller living rooms. A smart combination of space efficiency, contemporary styling, and everyday comfort.'),
    ('classic-model-headboard-bed', 'The Classic Model Headboard Bed combines timeless styling with a comfortable upholstered headboard for enhanced relaxation. Its padded surface provides convenient back support while reading, watching television, or resting. A versatile design that complements both classic and modern bedrooms.'),
    ('roman-model-bed', 'Inspired by classical Roman aesthetics, this bed features an elegant headboard with refined detailing and sophisticated proportions. Its strong construction provides dependable everyday support while creating a luxurious bedroom appearance. Ideal for customers seeking elegance, comfort, and distinctive design.'),
    ('luxury-headboard-bed', 'Featuring an oversized upholstered headboard, this premium bed creates an impressive statement within the bedroom. Rich cushioning and refined finishing provide both visual luxury and comfortable back support. Perfect for spacious master bedrooms and sophisticated premium interiors.'),
    ('round-shape-bed', 'The Round Shape Bed features a distinctive circular design that creates a bold and contemporary bedroom centerpiece. Its unique silhouette provides a spacious sleeping area while introducing a luxurious designer aesthetic. Ideal for modern bedrooms where creativity and individuality take center stage.'),
    ('dream-night-bed', 'The Dream Night Bed is designed to create a comfortable, peaceful, and welcoming environment for everyday relaxation. Its supportive construction and cushioned design provide dependable comfort while maintaining an elegant appearance. Perfect for creating a cozy and restful bedroom atmosphere.'),
    ('teak-wood-bed', 'Crafted from durable teak wood, this bed combines natural beauty with excellent strength and long-lasting construction. Its rich wood grain and warm finish create a timeless and sophisticated bedroom appearance. An ideal choice for customers who appreciate premium wooden furniture and traditional craftsmanship.'),
    ('polished-bed', 'The Polished Bed features a smooth and refined finish that adds elegance and sophistication to the bedroom. Its sturdy construction provides reliable everyday support while the polished surface enhances its premium appearance. A versatile design suitable for both contemporary and traditional interiors.'),
    ('shadhi-model-bed', 'The Shadhi Model Bed features ornate detailing inspired by traditional wedding furniture and luxurious bedroom designs. Its decorative headboard and premium finishing create an elegant and celebratory visual presence. Ideal for newlywed bedrooms and customers seeking traditional sophistication with statement styling.'),
    ('kerala-teak-bed', 'The Kerala Teak Bed combines premium wood craftsmanship with rich natural grain and exceptional structural strength. Its warm wooden finish and traditional character create a sophisticated and timeless bedroom atmosphere. An excellent choice for customers who value durability, craftsmanship, and authentic wooden furniture.'),
    ('inbuilt-plywood-bed', 'The Inbuilt Plywood Bed combines comfortable sleeping space with intelligently integrated storage for improved bedroom organization. Built-in compartments provide convenient space for bedding, clothing, and everyday essentials. An ideal space-saving solution for modern homes where functionality and clean design are equally important.')
)
update public.products as product
set short_description = catalogue.description,
    description = catalogue.description,
    updated_at = now()
from catalogue
where product.slug = catalogue.slug;
